'use client';
import { useEffect,useRef,useState } from 'react';
import { MessageSquare,Send,RefreshCw } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Textarea } from '@/components/ui/textarea';
import type { Snapshot,Thresholds } from '@/lib/monitoring';
import type { QuestionReply } from '@/lib/questions';
type Turn={id:number;question:string;reply:QuestionReply;capturedAt:string};
export function QuestionPanel({snapshot,thresholds}:{snapshot:Snapshot|null;thresholds:Thresholds}){
 const [question,setQuestion]=useState(''),[turns,setTurns]=useState<Turn[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState('');const lock=useRef(false),transcript=useRef<HTMLDivElement>(null);
 useEffect(()=>{if(transcript.current)transcript.current.scrollTop=transcript.current.scrollHeight;},[turns,busy]);
 async function ask(value=question){const q=value.trim();if(!q||!snapshot||lock.current)return;lock.current=true;setBusy(true);setError('');setQuestion(q);try{const r=await fetch('/api/chat',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({question:q,snapshot,thresholds,history:turns.slice(-6).map(t=>({question:t.question}))})});if(!r.ok)throw Error('暂时无法回答，请重试。');const reply=await r.json() as QuestionReply;setTurns(prev=>[...prev,{id:Date.now(),question:q,reply,capturedAt:snapshot.capturedAt}].slice(-12));setQuestion('');}catch(e){setError(e instanceof Error?e.message:'提问失败，请重试。');}finally{lock.current=false;setBusy(false);}}
 return <div className="question-panel"><div className="question-context"><MessageSquare size={16}/><span>基于当前采样和已保存阈值回答</span></div>{!turns.length&&<div className="question-welcome"><h3>想了解哪项资源？</h3><p>可查询 GPU、用户进程、存储余量和当前告警。</p><div className="question-suggestions">{['GPU5 是谁在用、运行什么任务？','哪个用户占用显存最多？','哪些磁盘需要关注？'].map(q=><Button variant="outline" key={q} disabled={!snapshot||busy} onClick={()=>void ask(q)}>{q}</Button>)}</div></div>}<div className="question-transcript" ref={transcript} aria-live="polite" aria-busy={busy}>{turns.map(t=><article className="question-turn" key={t.id}><div className="user-question"><span>你</span><p>{t.question}</p></div><div className="question-answer"><div className="answer-meta">模拟问答 · {new Date(t.capturedAt).toLocaleTimeString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'})} 采样{snapshot&&t.reply.snapshotId!==snapshot.id&&<em>历史采样</em>}</div><p>{t.reply.answer}</p>{t.reply.evidence.length>0&&<ul>{t.reply.evidence.map((e,i)=><li key={i}>{e}</li>)}</ul>}</div></article>)}</div>{busy&&<div className="question-loading"><RefreshCw size={14} className="spin"/>正在读取本次采样…</div>}{error&&<div className="question-error" role="alert">{error}</div>}<form className="question-form" onSubmit={e=>{e.preventDefault();void ask();}}><Textarea aria-label="向 Agent 提问" placeholder="例如：GPU5 是谁在用，运行什么任务？" maxLength={1000} value={question} disabled={busy} onChange={e=>setQuestion(e.target.value)} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();void ask();}}}/><div className="question-form-footer"><span>Enter 发送 · Shift+Enter 换行</span><Button type="submit" size="sm" disabled={!snapshot||busy||!question.trim()}><Send size={14}/>{busy?'回答中':'发送提问'}</Button></div></form><div className="question-disclaimer">模拟问答，尚未接入 LLM；不执行命令或修改阈值。</div></div>;
}
