'use client';
import { useState } from 'react';
import { Tabs,TabsList,TabsTrigger,TabsContent } from '@/components/ui/tabs';
import { Select,SelectTrigger,SelectValue,SelectContent,SelectItem } from '@/components/ui/select';
import { Table,TableHeader,TableBody,TableHead,TableRow,TableCell } from '@/components/ui/table';
import { Button } from '@/components/ui/button';
import { userStatistics } from '@/lib/questions';
import type { Snapshot } from '@/lib/monitoring';
export function ProcessViews({snapshot,children}:{snapshot:Snapshot|null;children:React.ReactNode}){
 const [tab,setTab]=useState('gpu'),[user,setUser]=useState('all');
 const stats=snapshot?userStatistics(snapshot):[],rows=(snapshot?.processes??[]).filter(p=>user==='all'||p.user===user);
 return <Tabs value={tab} onValueChange={setTab} className="process-tabs"><TabsList><TabsTrigger value="gpu">GPU 设备</TabsTrigger><TabsTrigger value="users">用户统计</TabsTrigger><TabsTrigger value="processes">进程明细</TabsTrigger></TabsList><TabsContent value="gpu">{children}</TabsContent><TabsContent value="users"><div className="process-summary">{stats.length} 位用户 · {new Set((snapshot?.processes??[]).map(p=>p.pid)).size} 个进程<span>按已归属显存排序</span></div><Table className="user-table"><TableHeader><TableRow><TableHead>用户</TableHead><TableHead>GPU</TableHead><TableHead>进程</TableHead><TableHead>显存</TableHead><TableHead>任务</TableHead><TableHead/></TableRow></TableHeader><TableBody>{stats.map(u=><TableRow key={u.user}><TableCell><strong>{u.user}</strong></TableCell><TableCell>{u.gpuIds.join(', ')}</TableCell><TableCell>{u.processCount}</TableCell><TableCell>{u.memoryUsed} GB</TableCell><TableCell>{u.tasks.join('、')}</TableCell><TableCell><Button variant="ghost" size="sm" onClick={()=>{setUser(u.user);setTab('processes');}}>查看进程</Button></TableCell></TableRow>)}</TableBody></Table>{!stats.length&&<div className="loading-state">{snapshot?'采样尚未提供用户归属数据。':'等待采样…'}</div>}<p className="process-note">跨 GPU 的同一 PID 只计为一个进程。显存按 GPU 分配量相加，GPU 使用率为整卡指标。</p></TabsContent><TabsContent value="processes"><div className="process-filter"><span>按用户查看</span><Select value={user} onValueChange={setUser}><SelectTrigger aria-label="进程用户筛选"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">全部用户</SelectItem>{stats.map(u=><SelectItem value={u.user} key={u.user}>{u.user}</SelectItem>)}</SelectContent></Select><span className="muted">{rows.length} 条 GPU 分配记录</span></div><Table className="process-table"><TableHeader><TableRow><TableHead>用户 / PID</TableHead><TableHead>GPU</TableHead><TableHead>显存</TableHead><TableHead>任务与启动命令</TableHead></TableRow></TableHeader><TableBody>{rows.map(p=><TableRow key={`${p.pid}-${p.gpuId}`}><TableCell><strong>{p.user}</strong><span className="process-pid">PID {p.pid}</span></TableCell><TableCell>GPU {p.gpuId}</TableCell><TableCell>{p.memoryUsed} GB</TableCell><TableCell><div>{p.task}</div><code>{p.command}</code></TableCell></TableRow>)}</TableBody></Table>{!rows.length&&<div className="loading-state">当前筛选没有进程记录。</div>}<p className="process-note">任务说明来自采集数据，不能仅凭命令确认进程是否异常。当前用户名与进程均为模拟数据。</p></TabsContent></Tabs>;
}
