import assert from 'node:assert/strict';
import {AssistantService,type AssistantRepository} from '../lib/assistant-service';
import {createMockSnapshot,defaults} from '../contracts/monitoring';
const rows={providers:new Map<string,string>(),sessions:new Map<string,string>()};
const repo:AssistantRepository={async list(k){return [...rows[k]].map(([id,data])=>({id,data}));},async put(k,id,d){rows[k].set(id,d);},async compareSession(id,expected,next){if(rows.sessions.get(id)!==expected)return false;rows.sessions.set(id,next);return true;},async remove(k,id){rows[k].delete(id);}};
let headers:Headers|undefined;let calls=0;let mode:'normal'|'delay'|'fail'='normal';
const fakeFetch:typeof fetch=async(_url,init)=>{calls++;if(mode==='fail')throw Error('test failure');headers=new Headers(init?.headers);const payload=init?.body?JSON.parse(String(init.body)):undefined;if(!payload)return Response.json({data:[{id:'test-model'}]});assert.equal(payload.chat_template_kwargs?.enable_thinking,false);if(!payload.stream)return Response.json({choices:[{message:{content:'OK'}}]});const encoder=new TextEncoder();if(mode==='delay')return new Response(new ReadableStream({start(c){c.enqueue(encoder.encode('data: {"choices":[{"delta":{"content":"部分回答"}}]}\n\n'));init?.signal?.addEventListener('abort',()=>c.error(Error('aborted')),{once:true});}}));return new Response(new ReadableStream({start(c){c.enqueue(encoder.encode('data: {"choices":[{"delta":{"content":"结论："}}]}\n\n'));c.enqueue(encoder.encode('data: {"choices":[{"delta":{"content":"GPU 有负载"}}]}\n\ndata: [DONE]\n\n'));c.close();}}));};
const svc=new AssistantService(repo,Buffer.alloc(32,1).toString('base64'),false,fakeFetch);
const provider=await svc.action({action:'saveProvider',provider:{name:'测试接口',baseUrl:'https://models.example.com/v1',disableThinking:true,apiKey:'test-key-disposable',models:['test-model'],enabled:true,isDefault:true}}) as {id:string};
assert.ok(!JSON.stringify(await svc.state()).includes('test-key-disposable'));
assert.ok(![...rows.providers.values()][0].includes('test-key-disposable'));
await svc.action({action:'saveProvider',provider:{id:provider.id,name:'测试接口',baseUrl:'https://models.example.com/v1',apiKey:'',models:['test-model'],enabled:true,isDefault:true}});
await svc.action({action:'test',id:provider.id,model:'test-model'});assert.equal(headers?.get('Authorization'),'Bearer test-key-disposable');
assert.deepEqual(await svc.action({action:'models',id:provider.id}),{models:['test-model']});
await assert.rejects(()=>svc.action({action:'saveProvider',provider:{name:'内网',baseUrl:'http://127.0.0.1:8080/v1',models:['m'],enabled:true,isDefault:false}}));
const session=await svc.action({action:'createSession'}) as {id:string};const snapshot=createMockSnapshot('pressure',0);
const response=await svc.action({action:'chat',sessionId:session.id,providerId:provider.id,model:'test-model',input:{question:'当前 GPU 状态？',snapshot,thresholds:defaults,history:[]}}) as Response;
const events=(await response.text()).trim().split('\n').map(e=>JSON.parse(e));assert.equal(events.at(-1).session.messages.at(-1).text,'结论：GPU 有负载');assert.equal((await svc.state()).sessions[0].messages.length,2);
await svc.action({action:'renameSession',id:session.id,title:'GPU 检查'});assert.equal((await svc.state()).sessions[0].title,'GPU 检查');
const mock=await svc.action({action:'chat',sessionId:session.id,providerId:'mock',model:'规则模拟',input:{question:'GPU5 上是谁在运行什么任务？',snapshot,thresholds:defaults,history:[]}}) as Response;assert.ok((await mock.text()).includes('rules-mock')===false);assert.ok((await svc.state()).sessions[0].messages.at(-1)?.evidence?.length);
mode='delay';
const request={action:'chat',sessionId:session.id,providerId:provider.id,model:'test-model',input:{question:'停止测试',snapshot,thresholds:defaults,history:[]}};
const delayed=await svc.action(request) as Response;
await assert.rejects(()=>svc.action(request),/正在生成/);
await assert.rejects(()=>svc.action({action:'renameSession',id:session.id,title:'竞争修改'}),/正在生成/);
const reader=delayed.body!.getReader();await reader.read();await reader.cancel();await new Promise(resolve=>setImmediate(resolve));
assert.equal((await svc.state()).sessions[0].messages.at(-1)?.status,'stopped');
mode='fail';const failed=await svc.action(request) as Response;await failed.text();assert.equal((await svc.state()).sessions[0].messages.at(-1)?.status,'error');mode='normal';
await svc.action({action:'saveProvider',provider:{id:provider.id,name:'测试接口',baseUrl:'https://models.example.com/v1',clearKey:true,models:['test-model'],enabled:true,isDefault:false}});assert.equal((await svc.state()).providers[0].hasKey,false);
await svc.action({action:'deleteSession',id:session.id});await svc.action({action:'deleteProvider',id:provider.id});assert.deepEqual(await svc.state(),{engine:"direct",providers:[],sessions:[]});
console.log('Assistant checks passed: encrypted keys, masked API, retain/clear key, endpoint validation, model discovery, connection test, streamed answer, mock evidence, session CRUD. Upstream requests:',calls);
