import type {AgentTool} from '@earendil-works/pi-agent-core';
import {Type,type TSchema} from 'typebox';
import {evaluate,analyzeSnapshot,type Snapshot,type Thresholds} from '../contracts/monitoring';
import {userStatistics} from '../contracts/questions';

/** All tools close over the same server-side sample; no filesystem or process execution. */
export function monitoringTools(snapshot:Snapshot,thresholds:Thresholds):AgentTool<any>[] {
 const gpuId=Type.Integer({minimum:0,maximum:63});
 const pagination={offset:Type.Optional(Type.Integer({minimum:0,maximum:10000})),limit:Type.Optional(Type.Integer({minimum:1,maximum:100}))};
 const schema=<T extends Record<string,TSchema>>(properties:T)=>Type.Object(properties,{additionalProperties:false});
 const metadata=()=>({snapshotId:snapshot.id,server:snapshot.server,capturedAt:snapshot.capturedAt,capturedAtBeijing:new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',dateStyle:'short',timeStyle:'medium',hourCycle:'h23'}).format(new Date(snapshot.capturedAt))+' UTC+8',source:snapshot.source,capacityUnit:snapshot.capacityUnit??'GB',sampleAgeMs:Date.now()-Date.parse(snapshot.capturedAt),stale:Date.now()-Date.parse(snapshot.capturedAt)>=120000});
 const result=(data:Record<string,unknown>)=>({content:[{type:'text' as const,text:JSON.stringify({...metadata(),...data})}],details:{snapshotId:snapshot.id}});
 const gpu=(id:number)=>{const value=snapshot.gpus.find(g=>g.id===id);if(!value)throw Error(`GPU ${id} 不存在。可用编号：${snapshot.gpus.map(g=>g.id).join(', ')}`);return value;};
 const page=<T>(rows:T[],args:{offset?:number;limit?:number})=>{const offset=args.offset??0,limit=args.limit??20;return {total:rows.length,offset,limit,returned:Math.max(0,Math.min(limit,rows.length-offset)),hasMore:offset+limit<rows.length,items:rows.slice(offset,offset+limit)};};
 const getGpuParameters=schema({gpuId});
 const getGpu:AgentTool<typeof getGpuParameters>={name:'get_gpu',label:'查询 GPU',description:'查询物理编号从 0 开始的一张 GPU 的当前指标、已保存阈值及进程。processCount 是匹配总数，最多返回显存占用最高的 20 条进程；更多进程用 get_processes 分页。',parameters:getGpuParameters,async execute(_id,args,signal){signal?.throwIfAborted();const device=gpu(args.gpuId);const rows=(snapshot.processes??[]).filter(p=>p.gpuId===device.id).sort((a,b)=>b.memoryUsed-a.memoryUsed);return result({gpu:device,processDataAvailable:snapshot.processes!==undefined,processCount:rows.length,processes:rows.slice(0,20),processesTruncated:rows.length>20,thresholds});}};
 const processParameters=schema({gpuId:Type.Optional(gpuId),user:Type.Optional(Type.String({minLength:1,maxLength:80})),pid:Type.Optional(Type.Integer({minimum:1})),...pagination});
 const processes:AgentTool<typeof processParameters>={name:'get_processes',label:'查询进程',description:'按 GPU 物理编号、用户名、PID 精确筛选当前采样进程，可组合条件，按显存占用降序分页。跨卡相同 PID 各保留一条 GPU 占用记录，uniqueProcessCount 对 PID 去重。dataAvailable=false 表示缺少进程数据，不能当作没有进程。未知任务用途仅为未知，不代表异常。',parameters:processParameters,async execute(_id,args,signal){signal?.throwIfAborted();if(args.gpuId!==undefined)gpu(args.gpuId);const rows=(snapshot.processes??[]).filter(p=>(args.gpuId===undefined||p.gpuId===args.gpuId)&&(args.user===undefined||p.user===args.user)&&(args.pid===undefined||p.pid===args.pid)).sort((a,b)=>b.memoryUsed-a.memoryUsed||a.pid-b.pid||a.gpuId-b.gpuId);return result({dataAvailable:snapshot.processes!==undefined,filters:{gpuId:args.gpuId,user:args.user,pid:args.pid},uniqueProcessCount:new Set(rows.map(p=>p.pid)).size,attributedMemoryUsed:rows.reduce((sum,p)=>sum+p.memoryUsed,0),...page(rows,args)});}};
 const userParameters=schema({user:Type.Optional(Type.String({minLength:1,maxLength:80})),...pagination});
 const users:AgentTool<typeof userParameters>={name:'get_users',label:'查询用户占用',description:'汇总当前采样用户的 GPU 编号、PID 去重进程数、任务及已归属显存，按显存占用降序分页；可精确筛选用户名。排名是按显存，不能代表 GPU 利用率或任务异常。显存为进程归属值，不含驱动及未归属占用。',parameters:userParameters,async execute(_id,args,signal){signal?.throwIfAborted();const rows=userStatistics(snapshot).filter(u=>args.user===undefined||u.user===args.user);return result({dataAvailable:snapshot.processes!==undefined,filterUser:args.user,rankingMetric:'attributedMemoryUsed',uniqueProcessCount:new Set((snapshot.processes??[]).filter(p=>args.user===undefined||p.user===args.user).map(p=>p.pid)).size,...page(rows,args)});}};
 const storageParameters=schema({mount:Type.Optional(Type.String({minLength:1,maxLength:100}))});
 const storage:AgentTool<typeof storageParameters>={name:'get_storage',label:'查询存储',description:'查询采样中的所有挂载点，或精确指定 mount。提供已用、总容量、普通用户可用空间、空闲空间和使用率；available 与 total-used 可因保留空间而不同。仅有挂载点容量，不能检查目录、文件或判断哪些文件可删除。',parameters:storageParameters,async execute(_id,args,signal){signal?.throwIfAborted();const rows=snapshot.disks.filter(d=>args.mount===undefined||d.mount===args.mount);if(args.mount!==undefined&&!rows.length)throw Error('采样中没有该挂载点：'+args.mount);const risks=evaluate(snapshot,thresholds,true);return result({diskThreshold:thresholds.disk,alertsEnabled:thresholds.enabled,disks:rows.map(d=>({...d,available:d.available??d.total-d.used,free:d.total-d.used,usagePercent:Math.round(d.used/d.total*1000)/10,thresholdExceeded:risks.some(a=>a.id==='disk-'+d.mount)}))});}};
 const alertParameters=schema({resource:Type.Optional(Type.String({minLength:1,maxLength:100})),severity:Type.Optional(Type.Union([Type.Literal('warning'),Type.Literal('critical')]))});
 const alerts:AgentTool<typeof alertParameters>={name:'get_alerts',label:'查询告警',description:'读取确定性规则按已保存阈值判断的告警，可按 resource（例如 GPU 4 或 /data）和 severity 筛选。alerts 是启用时的实际触发项；risks 是忽略暂停开关的阈值风险。暂停时 alerts 为空，但 risks 可以存在。模型不得改变阈值、宣称已通知或把高利用率直接认定为任务异常。',parameters:alertParameters,async execute(_id,args,signal){signal?.throwIfAborted();const filter=(a:ReturnType<typeof evaluate>[number])=>(args.resource===undefined||a.resource===args.resource)&&(args.severity===undefined||a.severity===args.severity);return result({enabled:thresholds.enabled,thresholds,overallStatus:analyzeSnapshot(snapshot,thresholds).status,filters:args,alerts:evaluate(snapshot,thresholds).filter(filter),risks:evaluate(snapshot,thresholds,true).filter(filter),notificationSent:false});}};
 return [getGpu,processes,users,storage,alerts];
}
