<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref,nextTick} from 'vue';
import ModelSettings from './ModelSettings.vue';
import AssistantPanel from './AssistantPanel.vue';
import {prepareQuestion} from './assistant';
import NavIcon from './NavIcon.vue';
import {ElMessage} from 'element-plus';
import {defaults,thresholdsSchema,scenarioNames,evaluate,alertText,type Snapshot,type Thresholds,type Scenario,type GPU} from '../../contracts/monitoring';
import {userStatistics} from '../../contracts/questions';
import {api} from './api';
import {copyText} from './clipboard';
import {observationState,resourceState} from '../../contracts/display-state';
const sections=[{id:'resources',label:'资源监控'},{id:'processes',label:'用户与进程'},{id:'alerts',label:'告警预览'},{id:'assistant',label:'AI 助手'},{id:'settings',label:'设置'}];
const section=ref('resources');
const desktopCollapsed=ref(false),isMobile=ref(false),mobileOpen=ref(false);
const collapsed=computed(()=>!isMobile.value&&desktopCollapsed.value);
const currentPage=computed(()=>sections.find(s=>s.id===section.value)?.label??'资源监控');
let media:MediaQueryList|undefined;
function syncViewport(){isMobile.value=media?.matches??false;mobileOpen.value=false;}
function toggleSidebar(){if(isMobile.value){mobileOpen.value=!mobileOpen.value;return;}desktopCollapsed.value=!desktopCollapsed.value;try{localStorage.setItem('server-watch-sidebar-collapsed',String(desktopCollapsed.value));}catch{}}
function navigate(id:string){section.value=id;mobileOpen.value=false;}
onUnmounted(()=>media?.removeEventListener('change',syncViewport));const scenario=ref<Scenario>('pressure');const snapshot=ref<Snapshot>();const loading=ref(false);const loadError=ref('');let tick=0;
const thresholds=ref<Thresholds>({...defaults}),draft=ref<Thresholds>({...defaults});
const settingsDirty=computed(()=>JSON.stringify(draft.value)!==JSON.stringify(thresholds.value));
const now=ref(Date.now());let ageTimer:ReturnType<typeof setInterval>|undefined;
onUnmounted(()=>clearInterval(ageTimer));
const observation=computed(()=>snapshot.value?observationState(snapshot.value,now.value,!!loadError.value):'failed');
const risks=computed(()=>snapshot.value?evaluate(snapshot.value,thresholds.value,true):[]);
const riskFor=(resource:string)=>risks.value.filter(a=>a.resource===resource);
const stateFor=(resource:string)=>resourceState(riskFor(resource),observation.value);
const riskDetail=(resource:string)=>{const state=stateFor(resource);return state.detail+(!thresholds.value.enabled?' 告警已暂停，资源阈值仍用于对照。':'');};
const users=computed(()=>snapshot.value?userStatistics(snapshot.value):[]);
const processes=computed(()=>snapshot.value?.processes??[]);
const alerts=computed(()=>snapshot.value?evaluate(snapshot.value,thresholds.value):[]);
const totalMemory=computed(()=>snapshot.value?.gpus.reduce((n,g)=>n+g.memoryUsed,0)??0);
const totalCapacity=computed(()=>snapshot.value?.gpus.reduce((n,g)=>n+g.memoryTotal,0)??0);
const distinctPids=computed(()=>new Set(processes.value.map(p=>p.pid)).size);
const userFilter=ref(''),gpuFilter=ref<number|undefined>(),query=ref('');
const filteredProcesses=computed(()=>processes.value.filter(p=>(!userFilter.value||p.user===userFilter.value)&&(gpuFilter.value===undefined||p.gpuId===gpuFilter.value)&&(!query.value||`${p.pid} ${p.command} ${p.task}`.toLowerCase().includes(query.value.toLowerCase()))));
const selectedGpu=ref<GPU>();const gpuOpen=ref(false);
const gpuProcesses=computed(()=>processes.value.filter(p=>p.gpuId===selectedGpu.value?.id));
const drawer=ref<'chat'|'report'|'email'|''>('');
const report=ref<Awaited<ReturnType<typeof api.analyze>>>();const reportBusy=ref(false);const reportError=ref('');
let thresholdsLoaded=false;const settingsError=ref('');const settingsReady=ref(false),settingsBusy=ref(false),serverThresholds=ref(false);const unit=computed(()=>snapshot.value?.capacityUnit??'GB');const currentTime=(s:string)=>new Date(s).toLocaleString('zh-CN',{hour12:false,timeZone:'Asia/Shanghai'});
const fmt=(value:number)=>Number(value.toFixed(2));
const pct=(used:number,total:number)=>Number((used/total*100).toFixed(1));
const owners=(id:number)=>[...new Set(processes.value.filter(p=>p.gpuId===id).map(p=>p.user))].join(', ')||'—';

async function refresh(){if(loading.value)return;loading.value=true;loadError.value='';try{snapshot.value=await api.monitor(scenario.value,tick++);now.value=Date.now();await loadThresholds();if(selectedGpu.value)selectedGpu.value=snapshot.value.gpus.find(g=>g.id===selectedGpu.value?.id);}catch(e){loadError.value=e instanceof Error?e.message:'采样失败';}finally{loading.value=false;}}
function openGpu(g:GPU){selectedGpu.value=g;gpuOpen.value=true;}
async function revealProcesses(){await nextTick();document.getElementById('process-table')?.scrollIntoView({behavior:'smooth',block:'start'});}
function filterUser(user:string){userFilter.value=user;gpuFilter.value=undefined;query.value='';void revealProcesses();}
function viewGpuProcesses(id:number){gpuOpen.value=false;userFilter.value='';gpuFilter.value=id;query.value='';navigate('processes');void revealProcesses();}
async function copyValue(value:string,label:string){try{await copyText(value);ElMessage.success(label+'已复制');}catch{ElMessage.error('复制失败，请手动选择文本');}}
function openChat(gpu?:number){gpuOpen.value=false;drawer.value='chat';if(gpu!==undefined)prepareQuestion(`GPU${gpu} 上是谁在运行什么任务？`);}
function askResource(question:string){prepareQuestion(question);drawer.value='chat';}
function openAssistant(gpu:number){gpuOpen.value=false;prepareQuestion(`分析 GPU${gpu} 的资源占用与用户进程，按结论、证据、建议、告警输出。`);navigate('assistant');}
function continueChat(){drawer.value='';navigate('assistant');}
async function analyze(){if(!snapshot.value||reportBusy.value)return;drawer.value='report';reportBusy.value=true;reportError.value='';try{report.value=await api.analyze(snapshot.value,thresholds.value);}catch(e){reportError.value=e instanceof Error?e.message:'分析失败';}finally{reportBusy.value=false;}}
async function saveSettings(){if(!settingsReady.value||settingsBusy.value)return;settingsBusy.value=true;const p=thresholdsSchema.safeParse(draft.value);if(!p.success){settingsError.value='检查阈值范围：使用率 1–100%，温度 30–110°C。';settingsBusy.value=false;return;}try{if(serverThresholds.value)await api.saveThresholds(p.data);else localStorage.setItem('server-watch-thresholds-v1',JSON.stringify(p.data));thresholds.value={...p.data};settingsError.value='';ElMessage.success(serverThresholds.value?'服务端阈值已保存':'浏览器阈值已保存');}catch{settingsError.value='阈值保存失败，生效值未改变，请重试。';}finally{settingsBusy.value=false;}}
async function copyAlert(){if(!snapshot.value)return;try{await copyText(alertText(snapshot.value,alerts.value));ElMessage.success('预览已复制');}catch{ElMessage.error('复制失败，可手动选择下方文本');}}
async function loadThresholds(){try{const value=await api.thresholds();serverThresholds.value=!!value;if(value){const dirty=settingsDirty.value;thresholds.value={...value};if(!dirty||!thresholdsLoaded)draft.value={...value};}thresholdsLoaded=true;settingsReady.value=true;settingsError.value='';}catch{settingsReady.value=false;settingsError.value='服务端阈值读取失败，请刷新重试。';}}
onMounted(()=>{ageTimer=setInterval(()=>{now.value=Date.now();if(snapshot.value?.source==='script')void refresh();},15000);media=window.matchMedia('(max-width:640px)');syncViewport();media.addEventListener('change',syncViewport);try{desktopCollapsed.value=localStorage.getItem('server-watch-sidebar-collapsed')==='true';}catch{}try{const raw=localStorage.getItem('server-watch-thresholds-v1');if(raw){const p=thresholdsSchema.safeParse(JSON.parse(raw));if(p.success){thresholds.value={...p.data};draft.value={...p.data};}}}catch{}void loadThresholds();void refresh();});
</script>
<template>
<div class="shell" :class="{'sidebar-collapsed':collapsed,'mobile-nav-open':mobileOpen}">
 <button v-if="isMobile&&mobileOpen" class="nav-overlay" aria-label="关闭导航" @click="mobileOpen=false"></button>
 <aside class="sidebar" id="main-navigation" aria-label="主导航"><div class="brand"><span class="brand-mark">SW</span><span v-if="!collapsed">Server Watch</span></div><el-menu :default-active="section" :collapse="collapsed" :collapse-transition="false" @select="navigate"><el-menu-item v-for="item in sections" :key="item.id" :index="item.id" :aria-label="item.label"><el-icon class="nav-icon"><NavIcon :name="item.id"/><span v-if="collapsed&&item.id==='alerts'&&alerts.length" class="collapsed-count">{{alerts.length}}</span></el-icon><template #title><span>{{item.label}}</span><span v-if="item.id==='settings'&&settingsDirty" class="pending-indicator" title="阈值有未保存修改" aria-label="阈值有未保存修改"></span><span v-if="item.id==='alerts'&&alerts.length" class="nav-count">{{alerts.length}}</span></template></el-menu-item></el-menu><div class="sidebar-foot"><template v-if="!collapsed">私有面板<span>原型 · v0.6</span></template><span v-else>私有</span></div></aside>
 <div class="workspace">
  <header class="topbar"><div class="top-navigation"><el-button class="collapse-button" text :aria-label="isMobile?(mobileOpen?'收起导航':'展开导航'):(collapsed?'展开侧边栏':'收起侧边栏')" :aria-expanded="isMobile?mobileOpen:!collapsed" aria-controls="main-navigation" @click="toggleSidebar"><NavIcon :name="collapsed||isMobile&&!mobileOpen?'unfold':'fold'"/></el-button><h1>{{currentPage}}</h1></div><div class="top-actions"><div class="server-name"><span class="server-dot"></span><strong>{{snapshot?.server??'等待采样'}}</strong><el-tag size="small" type="info" effect="plain">{{snapshot?.source==='script'?'真实采样':snapshot?'模拟数据':'等待采样'}}</el-tag></div><span class="sample-time">{{snapshot?currentTime(snapshot.capturedAt)+' CST':'等待采样'}}</span><el-button @click="openChat()">提问</el-button><el-button :loading="loading" @click="refresh">刷新</el-button></div></header>
  <main>
   <div class="page-toolbar"><div class="page-status"><el-tag v-if="!thresholds.enabled" size="small" type="info" effect="plain">告警暂停</el-tag><el-button v-if="settingsDirty&&section!=='settings'" link type="warning" @click="navigate('settings')">阈值修改未保存</el-button></div><div v-if="snapshot?.source==='mock'" class="scenario-control"><span>模拟场景</span><el-select v-model="scenario" aria-label="模拟场景" @change="refresh" :disabled="loading"><el-option v-for="(name,id) in scenarioNames" :key="id" :label="name" :value="id"/></el-select></div></div>
   <el-alert v-if="loadError" :title="loadError+(snapshot?'；保留上次成功采样，不能据此确认当前状态。':'')" type="error" :closable="false" show-icon/>
   <div v-if="!snapshot" class="initial-state">{{loading?'正在获取监控数据…':'暂无采样数据，点击刷新重试。'}}</div>
   <AssistantPanel v-if="section==='assistant'&&!snapshot" :snapshot="snapshot" :thresholds="thresholds"/>
   <template v-if="snapshot">
    <el-alert v-if="observation==='stale'" title="数据过期：采样已超过 2 分钟，请刷新后查看当前状态。" type="warning" :closable="false" show-icon/>
    <AssistantPanel v-if="section==='assistant'" :snapshot="snapshot" :thresholds="thresholds"/>
    <section v-show="section==='resources'">
     <div class="summary-strip"><div><span>GPU</span><strong>{{snapshot.gpus.length}}<small>张</small></strong></div><div><span>显存占用</span><strong>{{fmt(totalMemory)}}<small>/ {{fmt(totalCapacity)}} {{unit}}</small></strong></div><div><span>运行用户 / 进程</span><strong>{{users.length}}<small>/ {{distinctPids}}</small></strong></div><div><span>超阈值指标</span><strong :class="risks.length?'warning-text':''">{{risks.length}}<small>项<span v-if="observation!=='current'"> · 旧采样</span></small></strong></div></div>
     <div class="table-panel"><div class="panel-title"><h2>GPU 设备</h2><el-button text @click="analyze" :loading="reportBusy">查看分析</el-button></div><el-table :data="snapshot.gpus" @row-click="openGpu" class="gpu-table" row-key="id"><el-table-column label="GPU" width="95"><template #default="{row}"><span class="mono gpu-label">GPU {{row.id}}</span></template></el-table-column><el-table-column prop="name" label="型号" min-width="140"/><el-table-column label="利用率" min-width="135" align="right"><template #default="{row}"><span class="mono" :class="row.utilization>=thresholds.gpu?'warning-text':''">{{row.utilization}}%</span></template></el-table-column><el-table-column label="显存" prop="memoryUsed" sortable min-width="220" align="right"><template #default="{row}"><span class="mono memory-inline" :class="pct(row.memoryUsed,row.memoryTotal)>=thresholds.memory?'warning-text':''">{{fmt(row.memoryUsed)}} / {{fmt(row.memoryTotal)}} {{unit}} <span class="inline-percent">· {{pct(row.memoryUsed,row.memoryTotal)}}%</span></span></template></el-table-column><el-table-column label="温度" width="90" align="right"><template #default="{row}"><span class="mono" :class="row.temperature>=thresholds.temperature?'warning-text':''">{{row.temperature}}°C</span></template></el-table-column><el-table-column label="用户" min-width="155"><template #default="{row}">{{owners(row.id)}}</template></el-table-column><el-table-column label="进程" width="72" align="right"><template #default="{row}">{{processes.filter(p=>p.gpuId===row.id).length}}</template></el-table-column><el-table-column label="指标状态" width="135"><template #default="{row}"><el-tooltip :content="riskDetail('GPU '+row.id)" placement="top"><el-tag v-if="riskFor('GPU '+row.id).length||observation!=='current'" :type="stateFor('GPU '+row.id).tone" effect="plain" size="small">{{stateFor('GPU '+row.id).label}}</el-tag><span v-else class="quiet-status">低于阈值</span></el-tooltip></template></el-table-column></el-table><div class="table-foot">点击设备行查看进程；利用率为整卡指标，达到阈值不等于任务异常。</div></div>
     <div class="table-panel storage-panel"><div class="panel-title"><h2>存储</h2></div><el-table :data="snapshot.disks"><el-table-column label="挂载点" min-width="150"><template #default="{row}"><span class="mono">{{row.mount}}</span></template></el-table-column><el-table-column label="已用 / 总容量" min-width="170" align="right"><template #default="{row}"><span class="mono">{{fmt(row.used)}} / {{fmt(row.total)}} {{unit}}</span></template></el-table-column><el-table-column label="剩余" min-width="130" align="right"><template #default="{row}">{{fmt(row.available??row.total-row.used)}} {{unit}}</template></el-table-column><el-table-column label="使用率" min-width="160" align="right"><template #default="{row}"><span :class="pct(row.used,row.total)>=thresholds.disk?'warning-text':''">{{pct(row.used,row.total)}}%</span></template></el-table-column><el-table-column label="指标状态" width="135"><template #default="{row}"><el-tooltip :content="riskDetail(row.mount)" placement="top"><el-tag v-if="riskFor(row.mount).length||observation!=='current'" size="small" effect="plain" :type="stateFor(row.mount).tone">{{stateFor(row.mount).label}}</el-tag><span v-else class="quiet-status">低于阈值</span></el-tooltip></template></el-table-column></el-table></div>
    </section>
    <section v-show="section==='processes'">
     <div class="table-panel"><div class="panel-title"><h2>用户汇总</h2><span>{{users.length}} 位用户 · {{distinctPids}} 个进程</span></div><el-table :data="users"><el-table-column prop="user" label="用户" min-width="130"/><el-table-column label="GPU" min-width="180"><template #default="{row}"><span class="mono">{{row.gpuIds.map((n:number)=>'GPU '+n).join(', ')}}</span></template></el-table-column><el-table-column prop="processCount" label="进程数" sortable width="105" align="right"/><el-table-column label="显存" prop="memoryUsed" sortable width="135" align="right"><template #default="{row}">{{fmt(row.memoryUsed)}} {{unit}}</template></el-table-column><el-table-column label="任务" min-width="230"><template #default="{row}">{{row.tasks.join('、')}}</template></el-table-column><el-table-column label="操作" width="100"><template #default="{row}"><el-button link type="primary" @click="filterUser(row.user)">查看进程</el-button></template></el-table-column></el-table><div class="table-foot">跨卡 PID 在进程数中只计一次，显存按 GPU 分配累加。{{snapshot.source==='script'?'任务用途未知；命令参数已脱敏，显存可能有未归属开销。':'任务标签为模拟信息。'}}</div></div>
     <div class="table-panel" id="process-table"><div class="panel-title"><h2>进程明细</h2><span>{{filteredProcesses.length}} 条 GPU 分配</span></div><div class="filters"><el-select v-model="userFilter" clearable placeholder="全部用户" aria-label="用户筛选"><el-option v-for="u in users" :key="u.user" :label="u.user" :value="u.user"/></el-select><el-select v-model="gpuFilter" clearable placeholder="全部 GPU" aria-label="GPU 筛选"><el-option v-for="g in snapshot.gpus" :key="g.id" :label="'GPU '+g.id" :value="g.id"/></el-select><el-input v-model="query" clearable placeholder="搜索 PID、命令或任务" aria-label="搜索进程"/><el-button @click="userFilter='';gpuFilter=undefined;query=''">重置</el-button></div><div v-if="userFilter||gpuFilter!==undefined||query" class="filter-summary"><span>当前筛选</span><el-tag v-if="userFilter" closable size="small" @close="userFilter=''">用户：{{userFilter}}</el-tag><el-tag v-if="gpuFilter!==undefined" closable size="small" @close="gpuFilter=undefined">GPU {{gpuFilter}}</el-tag><el-tag v-if="query" closable size="small" @close="query=''">关键词：{{query}}</el-tag></div><el-table :data="filteredProcesses" empty-text="没有匹配的进程"><el-table-column prop="user" label="用户" width="120"/><el-table-column label="PID" width="95"><template #default="{row}"><span class="mono">{{row.pid}}</span></template></el-table-column><el-table-column label="GPU" width="85"><template #default="{row}">GPU {{row.gpuId}}</template></el-table-column><el-table-column label="显存" prop="memoryUsed" sortable width="115" align="right"><template #default="{row}">{{fmt(row.memoryUsed)}} {{unit}}</template></el-table-column><el-table-column prop="task" label="任务标签" min-width="155"/><el-table-column label="命令" min-width="300"><template #default="{row}"><code class="command">{{row.command}}</code></template></el-table-column></el-table></div>
    </section>
    <section v-show="section==='alerts'">
     <el-alert :title="thresholds.enabled?'仅展示当前采样的告警预览，尚未保存历史或发送邮件。':'告警已暂停；资源监控页仍显示达到阈值的指标。可在设置中启用。'" type="info" :closable="false"/>
     <div class="table-panel"><div class="panel-title"><h2>当前告警</h2><div><el-button @click="analyze" :loading="reportBusy">分析</el-button><el-button @click="drawer='email'">邮件预览</el-button></div></div><el-table :data="alerts" empty-text="当前没有触发告警"><el-table-column label="采样时间" min-width="175"><template #default>{{currentTime(snapshot.capturedAt)}}</template></el-table-column><el-table-column prop="resource" label="资源" width="110"/><el-table-column prop="metric" label="指标" min-width="150"/><el-table-column label="当前值" width="100" align="right"><template #default="{row}">{{row.value}}{{row.unit}}</template></el-table-column><el-table-column label="阈值" width="100" align="right"><template #default="{row}">{{row.threshold}}{{row.unit}}</template></el-table-column><el-table-column label="操作" width="85"><template #default="{row}"><el-button link type="primary" @click="askResource(row.resource+' 的'+row.metric+'达到阈值，请根据采样说明情况和建议。')">提问</el-button></template></el-table-column><el-table-column label="级别" width="105"><template #default="{row}"><el-tag size="small" effect="plain" :type="row.severity==='critical'?'danger':'warning'">{{row.severity==='critical'?'严重':'警告'}}</el-tag></template></el-table-column></el-table></div>
    </section>
    <section v-show="section==='settings'" class="settings-panel table-panel"><div class="panel-title"><h2>告警阈值</h2><el-tag :type="settingsDirty?'warning':'info'" effect="plain" size="small">{{settingsDirty?'未保存':'已应用'}}</el-tag></div><div v-if="settingsDirty" class="settings-pending" role="status">修改尚未生效，监控与告警仍使用已保存的阈值。</div><el-form label-position="left" label-width="145px" class="settings-form"><el-form-item label="启用告警"><el-switch v-model="draft.enabled"/><span class="field-hint">当前生效：{{thresholds.enabled?'启用':'暂停'}}；关闭后仍显示资源风险</span></el-form-item><el-form-item v-for="field in [{key:'gpu',label:'GPU 利用率',unit:'%',min:1,max:100},{key:'memory',label:'显存使用率',unit:'%',min:1,max:100},{key:'disk',label:'存储使用率',unit:'%',min:1,max:100},{key:'temperature',label:'GPU 温度',unit:'°C',min:30,max:110}] as const" :key="field.key" :label="field.label"><el-input-number v-model="draft[field.key]" :min="field.min" :max="field.max" :precision="0" :aria-label="field.label+'阈值'"/><span class="unit">{{field.unit}}</span><span class="field-hint">当前生效：{{thresholds[field.key]}}{{field.unit}} · 当前值 ≥ 阈值</span></el-form-item><el-alert v-if="settingsError" :title="settingsError" type="error" :closable="false"/><div class="settings-note">{{serverThresholds?'阈值保存在服务端，各设备刷新后同步。':'阈值保存在当前浏览器。'}}当前按单次采样判断，尚无持续时间和冷却窗口。</div><el-form-item><el-button type="primary" :disabled="!settingsReady||!settingsDirty" :loading="settingsBusy" @click="saveSettings">保存设置</el-button><el-button @click="draft={...defaults};settingsError=''">恢复默认</el-button><el-button text @click="draft={...thresholds};settingsError=''" :disabled="!settingsDirty">撤销修改</el-button></el-form-item></el-form></section>
   </template>
  </main><footer class="page-footer"><span>监控：{{snapshot?.source==='script'?'真实采样':'模拟采样'}} · 阈值：规则判断</span><span>{{snapshot?.source==='script'?'每 15 秒自动刷新':'手动刷新'}} · 时间为北京时间</span></footer>
 </div>
 <el-drawer v-model="gpuOpen" :title="selectedGpu?'GPU '+selectedGpu.id+' · 进程详情':'GPU 详情'" size="min(640px, 100%)">
  <template v-if="selectedGpu"><p v-if="selectedGpu.uuid" class="mono">{{selectedGpu.uuid}}</p><p v-if="selectedGpu.unattributedMemory!==undefined">未归属显存：{{fmt(selectedGpu.unattributedMemory)}} {{unit}}（驱动开销或采样差异）</p><div class="detail-metrics"><div><span>利用率</span><strong>{{selectedGpu.utilization}}%</strong></div><div><span>显存</span><strong>{{fmt(selectedGpu.memoryUsed)}} / {{fmt(selectedGpu.memoryTotal)}} {{unit}}</strong></div><div><span>温度</span><strong>{{selectedGpu.temperature}}°C</strong></div></div><div v-for="p in gpuProcesses" :key="p.pid" class="process-detail"><div><strong>{{p.user}}</strong><span class="mono">PID {{p.pid}} <el-button link type="primary" :aria-label="'复制 PID '+p.pid" @click="copyValue(String(p.pid),'PID')">复制</el-button></span><span>{{fmt(p.memoryUsed)}} {{unit}}</span></div><p>{{p.task}}<span v-if="p.startedAt"> · 启动于 {{currentTime(p.startedAt)}}</span></p><div class="command-heading"><span>启动命令</span><el-button link type="primary" :aria-label="'复制 PID '+p.pid+' 的命令'" @click="copyValue(p.command,'命令')">复制命令</el-button></div><code>{{p.command}}</code></div><div class="detail-actions"><el-button type="primary" @click="viewGpuProcesses(selectedGpu.id)">查看这张 GPU 的进程</el-button><el-button @click="openChat(selectedGpu.id)">询问这张 GPU</el-button><el-button @click="openAssistant(selectedGpu.id)">在 AI 助手中分析</el-button></div></template>
 </el-drawer>
 <el-drawer :model-value="drawer!==''" @close="drawer=''" :title="drawer==='chat'?'提问':drawer==='report'?'分析结果':'邮件预览'" size="min(620px, 100%)" class="assistant-drawer">
  <AssistantPanel v-if="drawer==='chat'" :snapshot="snapshot" :thresholds="thresholds" compact @continue="continueChat"/>
  <template v-if="drawer==='report'"><div class="drawer-meta">规则分析 · {{report?currentTime(report.generatedAt):'等待生成'}}</div><el-alert v-if="reportError" :title="reportError" type="error" :closable="false"/><div v-if="reportBusy">正在生成分析…</div><template v-else-if="report"><el-alert v-if="report.snapshotId!==snapshot?.id||JSON.stringify(report.thresholds)!==JSON.stringify(thresholds)" title="采样或阈值已更新，此结果属于之前的状态。" type="warning" :closable="false"/><section class="report-block"><h3>结论</h3><p>{{report.summary}}</p></section><section class="report-block"><h3>证据</h3><ul><li v-for="e in report.evidence" :key="e">{{e}}</li></ul></section><section class="report-block"><h3>建议</h3><ul><li v-for="e in report.recommendations" :key="e">{{e}}</li></ul></section><section class="report-block"><h3>告警</h3><p>{{report.thresholds.enabled?report.alerts.length+' 项指标触发告警。':'告警已暂停。'}}</p></section></template><el-button @click="analyze" :loading="reportBusy">重新分析</el-button></template>
  <template v-if="drawer==='email'"><div class="drawer-meta">未发送 · 内容来自当前采样</div><pre class="email-preview">{{snapshot?alertText(snapshot,alerts):''}}</pre><el-button @click="copyAlert">复制预览</el-button></template>
 </el-drawer>
 <ModelSettings/>
</div>
</template>
