<script setup lang="ts">
import {computed} from 'vue';
import type {ToolRecord} from '../../contracts/assistant';
const props=defineProps<{tool?:ToolRecord}>();
const data=computed(()=>{try{return JSON.parse(props.tool?.result??'null');}catch{return null;}});
const rows=computed(()=>{const d=data.value;return Array.isArray(d?.items)?d.items:Array.isArray(d?.processes)?d.processes:Array.isArray(d?.disks)?d.disks:Array.isArray(d?.risks)?d.risks:[];});
const columns=computed(()=>{if(!rows.value.length)return [];const known:Record<string,string>={user:'用户',pid:'PID',gpuId:'GPU',memoryUsed:'显存',processCount:'进程数',mount:'挂载点',used:'已用',total:'总容量',available:'可用',usagePercent:'使用率 %',resource:'资源',metric:'指标',value:'当前值',threshold:'阈值',severity:'级别',task:'任务'};return Object.entries(known).filter(([key])=>rows.value.some((r:any)=>r[key]!==undefined)).map(([key,label])=>({key,label:label+(['memoryUsed','used','total','available'].includes(key)?' ('+(data.value?.capacityUnit??'GB')+')':'')}));});
const number=(v:unknown)=>typeof v==='number'?v.toLocaleString('zh-CN',{maximumFractionDigits:2}):v;
const pretty=(v:unknown)=>typeof v==='string'?v:JSON.stringify(v,null,2);
const time=(s?:string)=>s?new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false}):'—';
</script>
<template><div v-if="tool" class="chat-tool-detail"><el-descriptions :column="1" border><el-descriptions-item label="工具">{{tool.name}}</el-descriptions-item><el-descriptions-item label="状态">{{({running:'调用中',complete:'已完成',error:'失败',stopped:'已停止'})[tool.status]}}</el-descriptions-item><el-descriptions-item label="开始">{{time(tool.startedAt)}}</el-descriptions-item><el-descriptions-item label="结束">{{time(tool.endedAt)}}</el-descriptions-item><el-descriptions-item v-if="data?.capturedAt" label="采样">{{time(data.capturedAt)}} · {{data.source==='script'?'真实采样':'模拟采样'}}</el-descriptions-item></el-descriptions><div v-if="data?.gpu" class="tool-gpu-metrics"><span>GPU {{data.gpu.id}}</span><strong>{{data.gpu.utilization}}% 利用率</strong><span>{{number(data.gpu.memoryUsed)}} / {{number(data.gpu.memoryTotal)}} {{data.capacityUnit}}</span></div><p v-if="data?.dataAvailable===false||data?.processDataAvailable===false" class="tool-note">当前采样缺少对应数据。</p><p v-if="data?.enabled===false" class="tool-note">告警已暂停，下面展示阈值风险。</p><el-table v-if="rows.length&&columns.length" :data="rows" max-height="360"><el-table-column v-for="column in columns" :key="column.key" :prop="column.key" :label="column.label" min-width="120"><template #default="{row}">{{number(row[column.key])}}</template></el-table-column></el-table><p v-if="data?.hasMore||data?.processesTruncated" class="tool-note">这是部分查询结果，更多记录需要再次查询。</p><el-collapse><el-collapse-item title="调用参数" name="args"><pre>{{pretty(tool.args)}}</pre></el-collapse-item><el-collapse-item title="原始结果" name="result"><pre>{{data?pretty(data):tool.result??'等待工具结果…'}}</pre></el-collapse-item></el-collapse></div></template>
<style scoped>
.chat-tool-detail{display:flex;flex-direction:column;gap:16px}.chat-tool-detail pre{padding:14px;background:#f6f8fb;border-radius:7px;font-size:12px;line-height:1.7;white-space:pre-wrap;overflow-wrap:anywhere;max-height:450px;overflow:auto}.tool-gpu-metrics{display:flex;flex-wrap:wrap;gap:14px;background:#eef4fc;padding:16px;border-radius:8px}.tool-note{font-size:12px;color:#7b889a;margin:0}
</style>
