<script setup lang="ts">
import {computed} from 'vue';
import {Conversations} from 'vue-element-plus-x';
import {assistant as a} from './assistant';
import type {Session} from '../../contracts/assistant';
const emit=defineEmits<{create:[];select:[];rename:[session:Session];remove:[session:Session]}>();
const day=(value:Date)=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(value);
const items=computed(()=>{const today=day(new Date()),yesterday=day(new Date(Date.now()-86400000));return a.sessions.filter(s=>s.title.toLowerCase().includes(a.query.toLowerCase())).sort((x,y)=>y.updatedAt.localeCompare(x.updatedAt)).map(s=>({...s,label:s.title,disabled:a.busy,group:day(new Date(s.updatedAt))===today?'今天':day(new Date(s.updatedAt))===yesterday?'昨天':'更早'}));});
const menu=computed(()=>[{key:'rename',command:'rename',label:'重命名',disabled:a.busy},{key:'remove',command:'remove',label:'删除会话',disabled:a.busy}]);
function command(action:unknown,item:any){if(a.busy)return;const session=a.sessions.find(s=>s.id===item.id);if(!session)return;if(action==='rename')emit('rename',session);if(action==='remove')emit('remove',session);}
</script>
<template><div class="chat-sessions"><div class="chat-session-heading"><span>会话</span><span>{{a.sessions.length}}</span></div><el-button class="chat-new" type="primary" plain @click="emit('create')" :disabled="a.busy||a.loading">＋ 新建会话</el-button><el-input v-model="a.query" placeholder="搜索会话" aria-label="搜索会话" clearable/><Conversations v-if="items.length" v-model:active="a.activeId" :items="items" row-key="id" label-key="label" :style="{width:'100%',height:'100%',padding:'0',backgroundColor:'transparent'}" :label-max-width="150" :groupable="{sort:(x:string,y:string)=>['今天','昨天','更早'].indexOf(x)-['今天','昨天','更早'].indexOf(y)}" :menu="menu" :show-built-in-menu="false" show-built-in-menu-type="always" :items-active-style="{backgroundColor:'#e9f0fa',color:'#2c5ea8'}" @change="emit('select')" @menu-command="command"><template #label="{item}"><button class="chat-session-label" :disabled="a.busy" :aria-pressed="a.activeId===item.id">{{item.label}}</button></template><template #more-filled="{item}"><button class="chat-session-more" :aria-label="'会话操作：'+item.label" :disabled="a.busy">⋯</button></template></Conversations><p v-else class="chat-no-sessions">{{a.loading?'正在加载会话…':a.query?'没有匹配的会话':'开始一次新的查询'}}</p><div class="chat-session-foot">会话保存在服务器</div></div></template>
<style scoped>
.chat-sessions{height:100%;display:flex;flex-direction:column;gap:14px;min-height:0}.chat-session-heading{display:flex;justify-content:space-between;font-size:13px;color:#708098;font-weight:600}.chat-new{width:100%}.chat-sessions :deep(.elx-conversations){flex:1;min-height:0;min-width:0;width:100%;max-width:100%;overflow:hidden}.chat-no-sessions{font-size:13px;color:#8491a3;text-align:center;margin:24px 0}.chat-session-foot{margin-top:auto;padding-top:12px;border-top:1px solid #e2e7ef;font-size:11px;color:#8592a3}.chat-sessions :deep(.elx-conversations-item){border-radius:7px}.chat-session-more{border:0;background:transparent;color:#8593a6;cursor:pointer;width:22px;height:22px;border-radius:4px;font-size:16px}.chat-session-more:hover{background:#e2eaf5}.chat-sessions :deep(.elx-conversations-item__dropdown-menu-container),.chat-sessions :deep(.elx-conversations-item__dropdown-more){display:block!important}.chat-session-label{font:inherit;font-size:13px;color:inherit;cursor:pointer;border:0;background:transparent;text-align:left;padding:0;width:100%;overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.chat-sessions :deep(.elx-conversations__list){width:100%;box-shadow:none}.chat-sessions :deep(.elx-conversations__group-title){font-size:11px}
</style>
