import {reactive,computed} from 'vue';
import type {AssistantState,Session,Provider} from '../../contracts/assistant';
import type {Snapshot,Thresholds} from '../../contracts/monitoring';
const state=reactive({engine:'direct' as 'pi'|'direct',providers:[] as Provider[],sessions:[] as Session[],activeId:'',selection:'mock',input:'',loading:false,loaded:false,busy:false,error:'',query:'',providerOpen:false});
const temporaryId=()=>`pending-${Date.now()}-${Math.random().toString(36).slice(2)}`;
let controller:AbortController|undefined;
export async function assistantAction<T=unknown>(action:string,body:Record<string,unknown>={}):Promise<T>{const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,...body}),signal:AbortSignal.timeout(25000)});const d=await r.json();if(!r.ok)throw Error(d.error??'请求失败');return d;}
export const activeSession=computed(()=>state.sessions.find(s=>s.id===state.activeId));
export const modelOptions=computed(()=>[{value:'mock',label:'规则模拟'},...state.providers.filter(p=>p.enabled).flatMap(p=>p.models.map(m=>({value:p.id+'|'+m,label:p.name+' / '+m})))]);
export async function loadAssistant(){if(state.loading||state.busy)return;state.loading=true;state.error='';try{const r=await fetch('/api/assistant',{cache:'no-store'});const d=await r.json() as AssistantState&{error?:string};if(!r.ok)throw Error(d.error??'加载失败');state.engine=d.engine??'direct';state.providers=d.providers;state.sessions=d.sessions;if(!state.sessions.some(s=>s.id===state.activeId))state.activeId=state.sessions[0]?.id??'';if(!state.loaded){const p=state.providers.find(p=>p.enabled&&p.isDefault);state.selection=p?p.id+'|'+p.models[0]:'mock';}if(!modelOptions.value.some(m=>m.value===state.selection))state.selection='mock';state.loaded=true;}catch(e){state.error=e instanceof Error?e.message:'加载失败';}finally{state.loading=false;}}
export async function newSession(){const s=await assistantAction<Session>('createSession');state.sessions.unshift(s);state.activeId=s.id;state.input='';return s;}
export function prepareQuestion(question:string){state.input=question;}
export async function sendQuestion(snapshot:Snapshot,thresholds:Thresholds){if(state.busy||!state.input.trim())return;state.busy=true;state.error='';controller=new AbortController();const question=state.input.trim();let started=false;
 try{const s=activeSession.value??await assistantAction<Session>('createSession');if(!state.sessions.some(x=>x.id===s.id))state.sessions.unshift(s);state.activeId=s.id;
 const [providerId,model]=state.selection==='mock'?['mock','规则模拟']:state.selection.split('|');const at=new Date().toISOString();const history=s.messages.filter(m=>m.role==='user').slice(-6).map(m=>({question:m.text}));const pending={id:temporaryId(),role:'assistant' as const,text:'',at,model:modelOptions.value.find(m=>m.value===state.selection)?.label??model,snapshotId:snapshot.id,capturedAt:snapshot.capturedAt};
 const r=await fetch('/api/assistant',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action:'chat',sessionId:s.id,providerId,model,input:{question,snapshot,thresholds,history}}),signal:controller.signal});if(!r.ok){const e=await r.json();throw Error(e.error??'提问失败');}
 started=true;state.input='';s.messages.push({id:temporaryId(),role:'user',text:question,at,model,snapshotId:snapshot.id,capturedAt:snapshot.capturedAt},pending);if(s.title==='新会话')s.title=question.slice(0,32);
 const reader=r.body!.getReader(),decoder=new TextDecoder();let buffer='';while(true){const chunk=await reader.read();if(chunk.done)break;buffer+=decoder.decode(chunk.value,{stream:true});const lines=buffer.split('\n');buffer=lines.pop()??'';for(const line of lines){if(!line)continue;const e=JSON.parse(line);const current=s.messages.at(-1)!;if(e.type==='context'){for(const message of s.messages.slice(-2)){message.snapshotId=e.snapshotId;message.capturedAt=e.capturedAt;}current.engine=e.engine;}if(e.type==='tool'){current.tools??=[];const index=current.tools.findIndex(t=>t.id===e.record.id);if(index<0)current.tools.push(e.record);else current.tools[index]=e.record;}if(e.type==='delta')current.text+=e.text;if(e.type==='error')state.error=e.error;if(e.type==='done'){const index=state.sessions.findIndex(x=>x.id===s.id);state.sessions[index]=e.session;}}}
 }catch(e){if(controller.signal.aborted){state.error='生成已停止';const last=activeSession.value?.messages.at(-1);if(last?.role==='assistant')last.status='stopped';}else state.error=e instanceof Error?e.message:'提问失败';if(!started)state.input=question;}
 finally{state.busy=false;controller=undefined;}
}
export function stopQuestion(){controller?.abort();}
export const assistant=state;
