<script setup lang="ts">
import {computed,ref} from 'vue';
import {ElMessage,ElMessageBox} from 'element-plus';
import type {Provider} from '../../contracts/assistant';
import {assistant as a,assistantAction,loadAssistant} from './assistant';
const blank=()=>({id:undefined as string|undefined,name:'',baseUrl:'',apiKey:'',clearKey:false,models:'',disableThinking:false,enabled:true,isDefault:false});const form=ref(blank()),editing=ref(false),busy=ref(false),error=ref(''),testResult=ref(''),models=ref<string[]>([]),testModel=ref('');
const selected=computed(()=>a.providers.find(p=>p.id===form.value.id));
function add(){form.value=blank();editing.value=true;error.value='';testResult.value='';models.value=[];testModel.value='';}
function edit(p:Provider){form.value={...p,disableThinking:p.disableThinking??false,apiKey:'',clearKey:false,models:p.models.join('\n')};editing.value=true;error.value='';testResult.value='';models.value=[];testModel.value=p.models[0];}
async function save(){busy.value=true;error.value='';try{const p=await assistantAction<Provider>('saveProvider',{provider:{...form.value,models:form.value.models.split(/[\n,，]/).map(m=>m.trim()).filter(Boolean)}});form.value.apiKey='';form.value.clearKey=false;await loadAssistant();edit(p);ElMessage.success('配置已保存到服务端');}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function remove(p:Provider){try{await ElMessageBox.confirm('删除服务商及其密钥？历史回答会保留。','删除服务商',{confirmButtonText:'删除',cancelButtonText:'取消'});await assistantAction('deleteProvider',{id:p.id});await loadAssistant();if(form.value.id===p.id)editing.value=false;}catch(e){if(e instanceof Error)error.value=e.message;}}
async function test(){if(!form.value.id)return;busy.value=true;error.value='';testResult.value='';try{const r=await assistantAction<{elapsedMs:number}>('test',{id:form.value.id,model:testModel.value});testResult.value=`连接成功 · ${r.elapsedMs} ms · ${testModel.value}`;}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
async function fetchModels(){if(!form.value.id)return;busy.value=true;error.value='';try{const r=await assistantAction<{models:string[]}>('models',{id:form.value.id});models.value=r.models;if(!models.value.length)error.value='接口没有返回模型，请手动填写。';}catch(e){error.value=(e as Error).message;}finally{busy.value=false;}}
function close(){form.value.apiKey='';form.value.clearKey=false;editing.value=false;error.value='';testResult.value='';}
</script>
<template><el-dialog v-model="a.providerOpen" title="模型与 API" width="min(900px, 96vw)" :close-on-click-modal="false" @closed="close">
<div class="provider-header"><span>OpenAI 兼容接口</span><el-button type="primary" @click="add" :disabled="busy">添加服务商</el-button></div>
<el-table :data="a.providers" empty-text="尚未配置服务商，可继续使用规则模拟"><el-table-column prop="name" label="服务商" min-width="130"/><el-table-column label="模型" min-width="160"><template #default="{row}">{{row.models.join('、')}}</template></el-table-column><el-table-column label="状态" width="110"><template #default="{row}">{{row.enabled?'启用':'停用'}}{{row.isDefault?' · 默认':''}}</template></el-table-column><el-table-column label="密钥" width="100"><template #default="{row}">{{row.hasKey?'已配置':'未配置'}}</template></el-table-column><el-table-column label="操作" width="140"><template #default="{row}"><el-button link type="primary" @click="edit(row)" :disabled="busy">编辑</el-button><el-button link type="danger" @click="remove(row)" :disabled="busy||a.busy">删除</el-button></template></el-table-column></el-table>
<el-form v-if="editing" label-width="110px" class="provider-form" @submit.prevent="save"><el-form-item label="服务商名称"><el-input v-model="form.name" maxlength="60" aria-label="服务商名称"/></el-form-item><el-form-item label="Base URL"><el-input v-model="form.baseUrl" placeholder="https://模型服务域名/v1" aria-label="Base URL"/><div class="config-hint">填接口根地址，通常以 /v1 结尾。托管版需要 HTTPS 域名；内网 vLLM 使用自部署后端。</div></el-form-item><el-form-item label="API Key"><el-input v-model="form.apiKey" type="password" show-password autocomplete="new-password" :placeholder="selected?.hasKey?'已配置 · 留空保留原密钥':'服务无需密钥时可留空'" aria-label="API Key"/><el-checkbox v-if="selected?.hasKey" v-model="form.clearKey">清除已保存密钥</el-checkbox><div class="config-hint">密钥加密保存在后端，读取配置不返回密钥。</div></el-form-item><el-form-item label="模型 ID"><el-input v-model="form.models" type="textarea" :rows="3" placeholder="每行一个模型 ID" aria-label="模型 ID"/><div class="config-hint">模型 ID 必须与服务端一致，不使用显示别名。</div></el-form-item><el-form-item label="思考模式"><el-checkbox v-model="form.disableThinking">关闭模型思考模式</el-checkbox><div class="config-hint">仅用于支持该选项的模型服务；保存后应用于后续回答。</div></el-form-item><el-form-item label="启用"><el-switch v-model="form.enabled"/><el-checkbox v-model="form.isDefault" style="margin-left:24px">作为默认服务商</el-checkbox></el-form-item><el-alert v-if="error" :title="error" type="error" :closable="false"/><el-alert v-if="testResult" :title="testResult" type="success" :closable="false"/><el-form-item><el-button type="primary" :loading="busy" :disabled="a.busy" @click="save">保存配置</el-button><el-button @click="editing=false;form.apiKey=''" :disabled="busy">取消编辑</el-button></el-form-item><div v-if="form.id" class="connection-tools"><p>以下操作使用已保存配置。连接测试会发送一条短请求。</p><el-select v-model="testModel" aria-label="测试模型"><el-option v-for="m in selected?.models" :key="m" :label="m" :value="m"/></el-select><el-button @click="test" :disabled="busy||!testModel">测试连接</el-button><el-button @click="fetchModels" :disabled="busy">获取模型列表</el-button><div v-if="models.length" class="discovered-models"><span>点击添加到编辑内容，保存后生效：</span><el-button v-for="m in models" :key="m" link type="primary" @click="form.models=[...new Set([...form.models.split('\n').filter(Boolean),m])].join('\n')">{{m}}</el-button></div></div></el-form>
<el-alert v-else-if="error" :title="error" type="error" :closable="false"/>
<template #footer><el-button @click="a.providerOpen=false" :disabled="busy">关闭</el-button></template></el-dialog></template>
