<script setup lang="ts">
import {watch,ref,onUnmounted} from 'vue';
import type {ProcessInference} from '../../contracts/inference';
const props=defineProps<{pid:number}>();const result=ref<ProcessInference>(),busy=ref(false),error=ref('');let token=0,controller:AbortController|undefined;
watch(()=>props.pid,async pid=>{const current=++token;controller?.abort();result.value=undefined;error.value='';busy.value=false;try{const r=await fetch('/api/process/inference?pid='+pid,{cache:'no-store'});if(!r.ok)return;const d=await r.json();if(current===token)result.value=d.inference??undefined;}catch{}},{immediate:true});onUnmounted(()=>{token++;controller?.abort();});
async function infer(refresh=false){const current=token;busy.value=true;error.value='';controller=new AbortController();try{const r=await fetch('/api/process/inference',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({pid:props.pid,refresh}),signal:controller.signal});const d=await r.json();if(!r.ok)throw Error(d.error??'推测失败');if(current===token)result.value=d;}catch(e){if(current===token)error.value=controller.signal.aborted?'已停止推测':(e as Error).message;}finally{if(current===token)busy.value=false;}}
</script>
<template><div class="process-inference"><el-button v-if="!busy" size="small" @click="infer(!!result)">{{result?'重新推测用途':'AI 推测用途'}}</el-button><el-button v-else size="small" @click="controller?.abort()">停止推测</el-button><p v-if="error" class="inference-error">{{error}}</p><div v-if="result"><p><el-tag size="small" type="info">AI 推测 · 未确认</el-tag> {{result.hypothesis}}</p><p>置信度：{{result.confidence==='medium'?'中':'低'}}（模型自评） · {{result.cached?'缓存 · ':''}}{{new Date(result.generatedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}}</p><el-collapse><el-collapse-item title="推测依据与限制" :name="pid"><ul><li v-for="item in result.evidence" :key="item">{{item}}</li></ul><ul><li v-for="item in result.limitations" :key="item">{{item}}</li></ul><p>采样：{{new Date(result.capturedAt).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}}</p></el-collapse-item></el-collapse></div></div></template>
<style scoped>.process-inference{margin-top:10px;font-size:12px;line-height:1.7}.inference-error{color:var(--el-color-danger)}</style>
