<script setup lang="ts">
import {computed,onMounted,onUnmounted,ref} from 'vue';
import type {StorageRoot,StorageListing,StorageJob} from '../../contracts/storage';
import {ElMessage} from 'element-plus';
const roots=ref<StorageRoot[]>([]),listing=ref<StorageListing>(),job=ref<StorageJob>(),busy=ref(false),error=ref('');let generation=0,timer:ReturnType<typeof setTimeout>|undefined;
const statuses={queued:'排队中',running:'统计中',complete:'已完成',partial:'部分统计',cancelled:'已取消',failed:'失败'};
const bytes=(n?:number)=>{if(n===undefined)return '—';const units=['B','KiB','MiB','GiB','TiB'];let i=0;while(n>=1024&&i<units.length-1){n/=1024;i++;}return n.toFixed(i?2:0)+' '+units[i];};
const time=(s:string)=>new Date(s).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
async function request<T>(path:string,body?:unknown):Promise<T>{const r=await fetch(path,{method:body===undefined?'GET':'POST',headers:body===undefined?{}:{'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body),signal:AbortSignal.timeout(20000),cache:'no-store'});if(r.status===404)throw Error('目录统计需要独立后端，当前接口不可用');const d=await r.json();if(!r.ok)throw Error(d.error??'目录请求失败');return d;}
const breadcrumbs=computed(()=>{const l=listing.value;if(!l)return [];const parts=l.path.slice(l.root.length).split('/').filter(Boolean);return [{label:l.root,path:l.root},...parts.map((label,i)=>({label,path:l.root.replace(/\/$/,'')+'/'+parts.slice(0,i+1).join('/')}))];});
const rows=computed(()=>listing.value?.entries.map(entry=>{const scanned=job.value?.rows.find(r=>r.path===entry.path);return {...entry,bytes:scanned?.bytes??entry.allocatedBytes,complete:scanned?.complete??entry.type!=='directory',errors:scanned?.errors??0,skippedMount:scanned?.skippedMount??entry.mount,ratio:job.value?.totalBytes&&scanned?+(scanned.bytes/job.value.totalBytes*100).toFixed(1):undefined};})??[]);
async function open(path:string,offset=0){const token=++generation;clearTimeout(timer);busy.value=true;error.value='';job.value=undefined;try{const list=await request<StorageListing>('/api/storage/list?'+new URLSearchParams({path,offset:String(offset)}));if(token!==generation)return;listing.value=list;const cached=await request<{job:StorageJob|null}>('/api/storage/cache?'+new URLSearchParams({path}));if(token===generation){job.value=cached.job??undefined;if(job.value&&['queued','running'].includes(job.value.status))void poll(job.value.id,token);}}catch(e){if(token===generation)error.value=(e as Error).message;}finally{if(token===generation)busy.value=false;}}
async function poll(id:string,token:number){try{const next=await request<StorageJob>('/api/storage/job?'+new URLSearchParams({id}));if(token!==generation)return;job.value=next;if(['queued','running'].includes(next.status))timer=setTimeout(()=>void poll(id,token),1000);}catch(e){if(token===generation)error.value=(e as Error).message;}}
async function scan(refresh=false){if(!listing.value)return;error.value='';const token=generation;try{const next=await request<StorageJob>('/api/storage/scan',{path:listing.value.path,refresh});if(token!==generation)return;job.value=next;if(['queued','running'].includes(next.status))void poll(next.id,token);}catch(e){error.value=(e as Error).message;}}
async function cancel(){if(!job.value)return;try{job.value=await request<StorageJob>('/api/storage/cancel',{id:job.value.id});clearTimeout(timer);}catch(e){ElMessage.error((e as Error).message);}}
async function treeLoad(node:any,resolve:(nodes:any[])=>void){if(node.level===0){resolve(roots.value.filter(r=>r.available).map(r=>({label:r.path,path:r.path})));return;}try{const list=await request<StorageListing>('/api/storage/list?'+new URLSearchParams({path:node.data.path,limit:'1000'}));resolve(list.entries.filter(e=>e.type==='directory').map(e=>({label:e.name+(e.mount?' · 挂载点':''),path:e.path})));if(list.hasMore||list.truncated)ElMessage.info('目录树仅展示前 1000 条；右侧明细可分页查看');}catch(e){resolve([]);ElMessage.error((e as Error).message);}}
onMounted(async()=>{try{roots.value=(await request<{roots:StorageRoot[]}>('/api/storage/roots')).roots;const root=roots.value.find(r=>r.available);if(root)await open(root.path);else error.value='没有可浏览的根目录，请检查后端配置与权限';}catch(e){error.value=(e as Error).message;}});onUnmounted(()=>{generation++;clearTimeout(timer);});
</script>
<template>
<section class="storage-browser"><el-alert v-if="error" :title="error" type="error" :closable="false"/>
 <div class="storage-roots"><el-button v-for="root in roots" :key="root.path" :disabled="!root.available" @click="open(root.path)">{{root.path}} · 可用 {{bytes(root.availableBytes)}} / 总 {{bytes(root.totalBytes)}}</el-button></div>
 <div class="storage-columns"><aside class="directory-tree"><h3>目录视图</h3><el-tree v-if="roots.length" node-key="path" lazy :load="treeLoad" :props="{label:'label',isLeaf:'leaf'}" @node-click="(node:any)=>open(node.path)"/><p class="muted">逐级展开 · 符号链接不展开</p></aside>
 <div class="directory-content"><div class="directory-toolbar"><el-button :disabled="!listing?.parent||busy" @click="listing?.parent&&open(listing.parent)">上一级</el-button><el-breadcrumb><el-breadcrumb-item v-for="b in breadcrumbs" :key="b.path"><el-button link @click="open(b.path)">{{b.label}}</el-button></el-breadcrumb-item></el-breadcrumb><el-button :disabled="!listing||busy||['queued','running'].includes(job?.status??'')" @click="scan()">统计当前目录</el-button><el-button :disabled="!listing||busy||['queued','running'].includes(job?.status??'')" @click="scan(true)">重新统计</el-button><el-button v-if="job&&['queued','running'].includes(job.status)" @click="cancel">取消统计</el-button></div>
 <p v-if="job" class="storage-job">{{statuses[job.status]}} · {{job.cached?'缓存 · ':''}}{{time(job.updatedAt)}} · 当前层合计 {{bytes(job.totalBytes)}}<span v-if="job.error"> · {{job.error}}</span><span v-if="job.errors"> · {{job.errors}} 项不可读取</span></p>
 <p class="muted">目录大小在点击统计后计算；采用实际磁盘占用，不跨文件系统。缓存有效期 15 分钟，统计结果不是实时值。</p>
 <el-alert v-if="listing?.truncated" title="当前目录超过 10000 项，列表已截断，请进入更小目录查看。" type="warning" :closable="false"/>
 <el-table :data="rows" v-loading="busy" row-key="path"><el-table-column label="名称" min-width="240"><template #default="{row}"><el-button v-if="row.type==='directory'&&row.readable" link type="primary" @click="open(row.path)">{{row.name}}/</el-button><span v-else>{{row.name}}</span><el-tag v-if="row.skippedMount" size="small" type="info">独立挂载点</el-tag></template></el-table-column><el-table-column label="类型" width="100"><template #default="{row}">{{({directory:'目录',file:'文件',symlink:'符号链接',other:'其他'} as Record<string,string>)[row.type]}}</template></el-table-column><el-table-column label="占用空间" prop="bytes" sortable align="right" min-width="140"><template #default="{row}">{{bytes(row.bytes)}}<span v-if="row.type==='directory'&&!row.complete&&!row.skippedMount"> · {{job&&['queued','running'].includes(job.status)?'统计中':'未完成'}}</span></template></el-table-column><el-table-column label="占父目录" align="right" width="110"><template #default="{row}">{{row.ratio===undefined?'—':row.ratio+'%'}}</template></el-table-column><el-table-column label="状态" width="150"><template #default="{row}">{{!row.readable?'不可读取':row.skippedMount?'单独进入统计':row.errors?'部分不可读取':row.type==='symlink'?'不跟随链接':row.type==='directory'&&!row.complete?'等待完整统计':'已统计'}}</template></el-table-column><el-table-column label="修改时间" min-width="170"><template #default="{row}">{{row.modifiedAt?time(row.modifiedAt):'—'}}</template></el-table-column></el-table>
 <div v-if="listing" class="directory-pages"><span>当前层 {{listing.total}} 项 · 展示 {{listing.total?listing.offset+1:0}}–{{listing.offset+listing.entries.length}}</span><el-button :disabled="listing.offset===0||busy" @click="open(listing.path,Math.max(0,listing.offset-100))">上一页</el-button><el-button :disabled="!listing.hasMore||busy" @click="open(listing.path,listing.offset+100)">下一页</el-button></div>
 </div></div>
</section>
</template>
<style scoped>
.storage-roots,.directory-toolbar,.directory-pages{display:flex;flex-wrap:wrap;align-items:center;gap:10px;margin-bottom:14px}.storage-columns{display:grid;grid-template-columns:240px minmax(0,1fr);gap:16px}.directory-tree,.directory-content{background:var(--el-bg-color);border:1px solid var(--el-border-color-light);padding:16px;border-radius:4px;min-width:0}.directory-tree{overflow:auto}.directory-tree h3{margin-top:0}.storage-job,.muted{font-size:12px;line-height:1.7;color:var(--el-text-color-secondary)}.directory-pages{justify-content:flex-end;margin-top:14px}.directory-pages span{margin-right:auto}.directory-toolbar .el-breadcrumb{flex:1;min-width:160px}@media(max-width:900px){.storage-columns{grid-template-columns:1fr}.directory-tree{max-height:240px}}
</style>
